namespace Blaggard {
  public enum CP437 {
    Null,
    WhiteSmilingFace,
    BlackSmilingFace,
    BlackHeartSuit,
    BlackDiamondSuit,
    BlackClubSuit,
    BlackSpadeSuit,
    Bullet,
    InverseBullet,
    WhiteCircle,
    InverseWhiteCircle,
    MaleSign,
    FemaleSign,
    EighthNote,
    BeamedEighthNotes,
    WhiteSunWithRays,

    BlackRightPointingPointer,
    BlackLeftPointingPointer,
    UpDownArrow,
    DoubleExclamationMark,
    PilcrowSign,
    SectionSign,
    BlackRectangle,
    UpDownArrowWithBase,
    UpwardsArrow,
    DownwardsArrow,
    RightwardsArrow,
    LeftwardsArrow,
    RightAngle,
    LeftRightArrow,
    BlackUpPointingTriangle,
    BlackDownPointingTriangle,

    Space,
    ExclamationMark,
    QuotationMark,
    NumberSign,
    DollarSign,
    PercentSign,
    Ampersand,
    Apostrophe,
    LeftParenthesis,
    RightParenthesis,
    Asterisk,
    PlusSign,
    Comma,
    HyphenMinus,
    FullStop,
    Solidus,

    DigitZero,
    DigitOne,
    DigitTwo,
    DigitThree,
    DigitFour,
    DigitFive,
    DigitSix,
    DigitSeven,
    DigitEight,
    DigitNine,
    Colon,
    Semicolon,
    LessThanSign,
    EqualsSign,
    GreaterThanSign,
    QuestionMark,

    CommercialAt,
    LatinCapitalLetterA,
    LatinCapitalLetterB,
    LatinCapitalLetterC,
    LatinCapitalLetterD,
    LatinCapitalLetterE,
    LatinCapitalLetterF,
    LatinCapitalLetterG,
    LatinCapitalLetterH,
    LatinCapitalLetterI,
    LatinCapitalLetterJ,
    LatinCapitalLetterK,
    LatinCapitalLetterL,
    LatinCapitalLetterM,
    LatinCapitalLetterN,
    LatinCapitalLetterO,

    LatinCapitalLetterP,
    LatinCapitalLetterQ,
    LatinCapitalLetterR,
    LatinCapitalLetterS,
    LatinCapitalLetterT,
    LatinCapitalLetterU,
    LatinCapitalLetterV,
    LatinCapitalLetterW,
    LatinCapitalLetterX,
    LatinCapitalLetterY,
    LatinCapitalLetterZ,
    LeftSquareBracket,
    ReverseSolidus,
    RightSquareBracket,
    CircumflexAccent,
    LowLine,

    GraveAccent,
    LatinSmallLetterA,
    LatinSmallLetterB,
    LatinSmallLetterC,
    LatinSmallLetterD,
    LatinSmallLetterE,
    LatinSmallLetterF,
    LatinSmallLetterG,
    LatinSmallLetterH,
    LatinSmallLetterI,
    LatinSmallLetterJ,
    LatinSmallLetterK,
    LatinSmallLetterL,
    LatinSmallLetterM,
    LatinSmallLetterN,
    LatinSmallLetterO,

    LatinSmallLetterP,
    LatinSmallLetterQ,
    LatinSmallLetterR,
    LatinSmallLetterS,
    LatinSmallLetterT,
    LatinSmallLetterU,
    LatinSmallLetterV,
    LatinSmallLetterW,
    LatinSmallLetterX,
    LatinSmallLetterY,
    LatinSmallLetterZ,
    LeftCurlyBracket,
    VerticalLine,
    RightCurlyBracket,
    Tilde,
    House,

    LatinCapitalLetterCWithCedilla,
    LatinSmallLetterUWithDiaeresis,
    LatinSmallLetterEWithAcute,
    LatinSmallLetterAWithCircumflex,
    LatinSmallLetterAWithDiaeresis,
    LatinSmallLetterAWithGrave,
    LatinSmallLetterAWithRingAbove,
    LatinSmallLetterCWithCedilla,
    LatinSmallLetterEWithCircumflex,
    LatinSmallLetterEWithDiaeresis,
    LatinSmallLetterEWithGrave,
    LatinSmallLetterIWithDiaeresis,
    LatinSmallLetterIWithCircumflex,
    LatinSmallLetterIWithGrave,
    LatinCapitalLetterAWithDiaeresis,
    LatinCapitalLetterAWithRingAbove,

    LatinCapitalLetterEWithAcute,
    LatinSmallLetterAe,
    LatinCapitalLetterAe,
    LatinSmallLetterOWithCircumflex,
    LatinSmallLetterOWithDiaeresis,
    LatinSmallLetterOWithGrave,
    LatinSmallLetterUWithCircumflex,
    LatinSmallLetterUWithGrave,
    LatinSmallLetterYWithDiaeresis,
    LatinCapitalLetterOWithDiaeresis,
    LatinCapitalLetterUWithDiaeresis,
    CentSign,
    PoundSign,
    YenSign,
    PesetaSign,
    LatinSmallLetterFWithHook,

    LatinSmallLetterAWithAcute,
    LatinSmallLetterIWithAcute,
    LatinSmallLetterOWithAcute,
    LatinSmallLetterUWithAcute,
    LatinSmallLetterNWithTilde,
    LatinCapitalLetterNWithTilde,
    FeminineOrdinalIndicator,
    MasculineOrdinalIndicator,
    InvertedQuestionMark,
    ReversedNotSign,
    NotSign,
    VulgarFractionOneHalf,
    VulgarFractionOneQuarter,
    InvertedExclamationMark,
    LeftPointingDoubleAngleQuotationMark,
    RightPointingDoubleAngleQuotationMark,

    LightShade,
    MediumShade,
    DarkShade,
    BoxDrawingsLightVertical,
    BoxDrawingsLightVerticalAndLeft,
    BoxDrawingsVerticalSingleAndLeftDouble,
    BoxDrawingsVerticalDoubleAndLeftSingle,
    BoxDrawingsDownDoubleAndLeftSingle,
    BoxDrawingsDownSingleAndLeftDouble,
    BoxDrawingsDoubleVerticalAndLeft,
    BoxDrawingsDoubleVertical,
    BoxDrawingsDoubleDownAndLeft,
    BoxDrawingsDoubleUpAndLeft,
    BoxDrawingsUpDoubleAndLeftSingle,
    BoxDrawingsUpSingleAndLeftDouble,
    BoxDrawingsLightDownAndLeft,

    BoxDrawingsLightUpAndRight,
    BoxDrawingsLightUpAndHorizontal,
    BoxDrawingsLightDownAndHorizontal,
    BoxDrawingsLightVerticalAndRight,
    BoxDrawingsLightHorizontal,
    BoxDrawingsLightVerticalAndHorizontal,
    BoxDrawingsVerticalSingleAndRightDouble,
    BoxDrawingsVerticalDoubleAndRightSingle,
    BoxDrawingsDoubleUpAndRight,
    BoxDrawingsDoubleDownAndRight,
    BoxDrawingsDoubleUpAndHorizontal,
    BoxDrawingsDoubleDownAndHorizontal,
    BoxDrawingsDoubleVerticalAndRight,
    BoxDrawingsDoubleHorizontal,
    BoxDrawingsDoubleVerticalAndHorizontal,
    BoxDrawingsUpSingleAndHorizontalDouble,

    BoxDrawingsUpDoubleAndHorizontalSingle,
    BoxDrawingsDownSingleAndHorizontalDouble,
    BoxDrawingsDownDoubleAndHorizontalSingle,
    BoxDrawingsUpDoubleAndRightSingle,
    BoxDrawingsUpSingleAndRightDouble,
    BoxDrawingsDownSingleAndRightDouble,
    BoxDrawingsDownDoubleAndRightSingle,
    BoxDrawingsVerticalDoubleAndHorizontalSingle,
    BoxDrawingsVerticalSingleAndHorizontalDouble,
    BoxDrawingsLightUpAndLeft,
    BoxDrawingsLightDownAndRight,
    FullBlock,
    LowerHalfBlock,
    LeftHalfBlock,
    RightHalfBlock,
    UpperHalfBlock,

    GreekSmallLetterAlpha,
    LatinSmallLetterSharpS,
    GreekCapitalLetterGamma,
    GreekSmallLetterPi,
    GreekCapitalLetterSigma,
    GreekSmallLetterSigma,
    MicroSign,
    GreekSmallLetterTau,
    GreekCapitalLetterPhi,
    GreekCapitalLetterTheta,
    GreekCapitalLetterOmega,
    GreekSmallLetterDelta,
    Infinity,
    GreekSmallLetterPhi,
    GreekSmallLetterEpsilon,
    Intersection,

    IdenticalTo,
    PlusMinusSign,
    GreaterThanOrEqualTo,
    LessThanOrEqualTo,
    TopHalfIntegral,
    BottomHalfIntegral,
    DivisionSign,
    AlmostEqualTo,
    DegreeSign,
    BulletOperator,
    MiddleDot,
    SquareRoot,
    SuperscriptLatinSmallLetterN,
    SuperscriptTwo,
    BlackSquare,
    NoBreakSpace,
  }

  public static class CP437Utils {
    public static int FromChar(char ch) => ch switch {
      var _ when ch == 0 || (ch > 0x1F && ch < 0x7E) => ch,
      '☺' => 1,
      '☻' => 2,
      '♥' => 3,
      '♦' => 4,
      '♣' => 5,
      '♠' => 6,
      '•' => 7,
      '◘' => 8,
      '○' => 9,
      '◙' => 10,
      '♂' => 11,
      '♀' => 12,
      '♪' => 13,
      '♫' => 14,
      '☼' => 15,

      '►' => 16,
      '◄' => 17,
      '↕' => 18,
      '‼' => 19,
      '¶' => 20,
      '§' => 21,
      '▬' => 22,
      '↨' => 23,
      '↑' => 24,
      '↓' => 25,
      '→' => 26,
      '←' => 27,
      '∟' => 28,
      '↔' => 29,
      '▲' => 30,
      '▼' => 31,

      '⌂' => 127,

      'Ç' => 128,
      'ü' => 129,
      'é' => 130,
      'â' => 131,
      'ä' => 132,
      'à' => 133,
      'å' => 134,
      'ç' => 135,
      'ê' => 136,
      'ë' => 137,
      'è' => 138,
      'ï' => 139,
      'î' => 140,
      'ì' => 141,
      'Ä' => 142,
      'Å' => 143,

      'É' => 144,
      'æ' => 145,
      'Æ' => 146,
      'ô' => 147,
      'ö' => 148,
      'ò' => 149,
      'û' => 150,
      'ù' => 151,
      'ÿ' => 152,
      'Ö' => 153,
      'Ü' => 154,
      '¢' => 155,
      '£' => 156,
      '¥' => 157,
      '₧' => 158,
      'ƒ' => 159,

      'á' => 160,
      'í' => 161,
      'ó' => 162,
      'ú' => 163,
      'ñ' => 164,
      'Ñ' => 165,
      'ª' => 166,
      'º' => 167,
      '¿' => 168,
      '⌐' => 169,
      '¬' => 170,
      '½' => 171,
      '¼' => 172,
      '¡' => 173,
      '«' => 174,
      '»' => 175,

      '░' => 176,
      '▒' => 177,
      '▓' => 178,
      '│' => 179,
      '┤' => 180,
      '╡' => 181,
      '╢' => 182,
      '╖' => 183,
      '╕' => 184,
      '╣' => 185,
      '║' => 186,
      '╗' => 187,
      '╝' => 188,
      '╜' => 189,
      '╛' => 190,
      '┐' => 191,

      '└' => 192,
      '┴' => 193,
      '┬' => 194,
      '├' => 195,
      '─' => 196,
      '┼' => 197,
      '╞' => 198,
      '╟' => 199,
      '╚' => 200,
      '╔' => 201,
      '╩' => 202,
      '╦' => 203,
      '╠' => 204,
      '═' => 205,
      '╬' => 206,
      '╧' => 207,

      '╨' => 208,
      '╤' => 209,
      '╥' => 210,
      '╙' => 211,
      '╘' => 212,
      '╒' => 213,
      '╓' => 214,
      '╫' => 215,
      '╪' => 216,
      '┘' => 217,
      '┌' => 218,
      '█' => 219,
      '▄' => 220,
      '▌' => 221,
      '▐' => 222,
      '▀' => 223,

      'α' => 224,
      'ß' => 225,
      'Γ' => 226,
      'π' => 227,
      'Σ' => 228,
      'σ' => 229,
      'µ' => 230,
      'τ' => 231,
      'Φ' => 232,
      'Θ' => 233,
      'Ω' => 234,
      'δ' => 235,
      '∞' => 236,
      'φ' => 237,
      'ε' => 238,
      '∩' => 239,

      '≡' => 240,
      '±' => 241,
      '≥' => 242,
      '≤' => 243,
      '⌠' => 244,
      '⌡' => 245,
      '÷' => 246,
      '≈' => 247,
      '°' => 248,
      '∙' => 249,
      '·' => 250,
      '√' => 251,
      'ⁿ' => 252,
      '²' => 253,
      '■' => 254,
      '□' => 255,

      _ => 0,
    };
  }
}
